name    'replica-set-verifier'
version '0.1.0'
source 'https://github.com/Johaned/replica-set-verifier-puppet'
author 'Johan Tique'
license 'Apache License, Version 2.0'
summary 'This module install LIBSON, MONGO-C-Driver and replica-set-verifier service'
description 'Puppet module for replica-set-verifier'
project_page 'UNKNOWN'
dependency   'puppetlabs/stdlib', '>= 2.2.1'
